### ISSUE TITLE
ci: add `svelte-check`

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#184]
### Description

1. Add `Check` step to CI pipeline (`.github/workflows/format-lint-test.yaml`) after `Lint` step:

```yaml
- name: Check
  working-directory: ./unime
  run: npm run check
```

2. Iterate through all `// eslint-disable-next-line` and resolve or add comment why they should be kept

### Motivation

Enhance code quality

### Requirements

n/a

### Open Questions

n/a

### Are you planning to contribute this in a PR?

Yes
